test = TreeModel([0, 15, 45, 85, 185, 285, 385]);
% test.num_periods
% test.num_decision_nodes
% test.num_final_states
% test.get_num_nodes_period(2)
% test.get_num_nodes_period(5)
% test.final_state_probs
% test.all_node_probs
% test.get_node(1,1)
% test.get_node(4,10)
% test.get_nodes_in_period(0)
% test.get_nodes_in_period(1)
% test.get_nodes_in_period(4)
% test.get_period(0)
% test.get_period(4)
% test.get_state(0)
% test.get_state(4)
% test.get_parentnode(2)
% test.get_parentnode(4)
% test.get_parentnode(10)
% test.get_path(2)
% test.get_path(4)
% test.get_path(62)
% test.get_probs_in_period(2)
% test.get_probs_in_period(4)
% test.reachable_end_state(0)
% test.reachable_end_state(10)
% test.reachable_end_state(32)